import { useCallback, useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { IssueMap } from '../../IssueMap';
import { IssuePhotos } from '../../IssuePhotos';
import { getIssue, getIssueUpdates } from '../../issues';
import { colors } from '../../theme';
import type { PublicIssue } from '../../types';
import { dateLabel, EmptyState, StatusBadge, statusLabel } from '../../ui';

type Update = { id: string; status: PublicIssue['status']; public_message: string | null; created_at: string };
export default function IssueDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [issue, setIssue] = useState<PublicIssue | null>(null); const [updates, setUpdates] = useState<Update[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { if (!id) return; let active = true; setLoading(true); Promise.all([getIssue(id), getIssueUpdates(id)]).then(([item, history]) => { if (active) { setIssue(item); setUpdates(history as Update[]); setError(''); } }).catch(() => { if (active) setError('Could not load this report. Please try again.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]));
  return <SafeAreaView edges={['top', 'bottom']} style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable accessibilityLabel="Go back" onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)')} style={s.back}><Ionicons name="arrow-back" size={20} color={colors.ink} /><Text style={s.backText}>Back</Text></Pressable>{loading ? <ActivityIndicator color={colors.accent} style={{ margin: 50 }} /> : error || !issue ? <EmptyState icon="alert-circle-outline" title="Report unavailable" detail={error || 'This report may no longer be public.'} /> : <><Text style={s.eyebrow}>{issue.public_id} · {issue.category?.name ?? 'Civic issue'}</Text><Text style={s.title}>{issue.title}</Text><View style={s.status}><StatusBadge status={issue.status} /><Text style={s.updated}>Updated {dateLabel(issue.updated_at)}</Text></View><View style={s.card}><Text style={s.sectionTitle}>What was reported</Text><Text style={s.body}>{issue.description}</Text><View style={s.rule} /><View style={s.meta}><Ionicons name="location-outline" size={19} color={colors.accent} /><Text style={s.metaText}>{issue.address}</Text></View><View style={s.meta}><Ionicons name="business-outline" size={19} color={colors.accent} /><Text style={s.metaText}>{issue.department?.name ?? 'Awaiting department'}</Text></View></View><IssuePhotos issueId={issue.id} />{issue.latitude != null && issue.longitude != null && <View style={s.map}><Text style={s.sectionTitle}>Reported location</Text><IssueMap center={{ latitude: issue.latitude, longitude: issue.longitude }} selected={{ latitude: issue.latitude, longitude: issue.longitude }} /></View>}<View style={s.history}><Text style={s.sectionTitle}>Progress updates</Text>{updates.length ? updates.map((update, index) => <View key={update.id} style={s.update}><View style={s.timeline}><View style={s.timelineDot} />{index < updates.length - 1 && <View style={s.timelineLine} />}</View><View style={{ flex: 1 }}><Text style={s.updateTitle}>{statusLabel[update.status]}</Text><Text style={s.updateDate}>{dateLabel(update.created_at)}</Text>{update.public_message && <Text style={s.updateMessage}>{update.public_message}</Text>}</View></View>) : <Text style={s.body}>No public updates yet.</Text>}</View></>}</ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, content: { maxWidth: 800, width: '100%', alignSelf: 'center', padding: 20, paddingBottom: 40 }, back: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, marginBottom: 25 }, backText: { color: colors.ink, fontFamily: 'Inter_600SemiBold', fontSize: 13 }, eyebrow: { color: colors.accent, fontFamily: 'Inter_600SemiBold', fontSize: 11, letterSpacing: 1 }, title: { color: colors.ink, fontFamily: 'SpaceGrotesk_700Bold', fontSize: 29, lineHeight: 35, marginTop: 8, letterSpacing: -.8 }, status: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 17, marginBottom: 23 }, updated: { color: colors.muted, fontFamily: 'Inter_400Regular', fontSize: 12 }, card: { backgroundColor: colors.paperRaised, borderRadius: 20, borderWidth: 1, borderColor: colors.rule, padding: 20 }, sectionTitle: { color: colors.ink, fontFamily: 'SpaceGrotesk_700Bold', fontSize: 19, marginBottom: 13 }, body: { color: colors.inkSoft, fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 22 }, rule: { borderTopWidth: 1, borderColor: colors.rule, marginVertical: 19 }, meta: { flexDirection: 'row', gap: 10, alignItems: 'center', marginBottom: 11 }, metaText: { flex: 1, color: colors.inkSoft, fontFamily: 'Inter_500Medium', fontSize: 13 }, map: { marginTop: 26 }, history: { marginTop: 28, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, borderRadius: 20, padding: 20 }, update: { flexDirection: 'row', gap: 13, minHeight: 70 }, timeline: { alignItems: 'center', width: 16 }, timelineDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.accent, marginTop: 3 }, timelineLine: { flex: 1, width: 2, backgroundColor: colors.ruleStrong, marginTop: 5 }, updateTitle: { color: colors.ink, fontFamily: 'Inter_600SemiBold', fontSize: 13 }, updateDate: { color: colors.muted, fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, updateMessage: { color: colors.inkSoft, fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 6 } });
