import { useCallback, useMemo, useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import * as Location from 'expo-location';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { IssueMap, type Coordinate } from '../../IssueMap';
import { getPublicIssues } from '../../issues';
import { isSupabaseConfigured } from '../../supabase';
import { colors } from '../../theme';
import type { IssueStatus, PublicIssue } from '../../types';
import { EmptyState, IssueCard, SectionHeading } from '../../ui';

const filters: { label: string; value: IssueStatus | 'all' }[] = [{ label: 'All', value: 'all' }, { label: 'Received', value: 'new' }, { label: 'In progress', value: 'in_progress' }, { label: 'Resolved', value: 'resolved' }];
export default function Explore() {
  const [issues, setIssues] = useState<PublicIssue[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState<IssueStatus | 'all'>('all');
  const [search, setSearch] = useState('');
  const [center, setCenter] = useState<Coordinate | null>(null);
  const [selected, setSelected] = useState<PublicIssue | null>(null);
  useFocusEffect(useCallback(() => { let active = true; if (!isSupabaseConfigured) { setLoading(false); setError('Connect Supabase to browse reports.'); return; } setLoading(true); getPublicIssues().then(data => { if (active) { setIssues(data); setError(''); } }).catch(() => { if (active) setError('Could not load reports. Reopen Explore to retry.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []));
  const shown = useMemo(() => issues.filter(item => (filter === 'all' || item.status === filter) && `${item.title} ${item.address} ${item.public_id}`.toLowerCase().includes(search.toLowerCase().trim())), [issues, filter, search]);
  const locate = async () => { try { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return Alert.alert('Location is off', 'Enable location permission to center the map on your area.'); const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setCenter(position.coords); } catch { Alert.alert('Location unavailable', 'Please try again or explore the map manually.'); } };
  return <SafeAreaView edges={['top']} style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.header}><View><Text style={s.eyebrow}>NEIGHBORHOOD VIEW</Text><Text style={s.title}>Explore issues</Text><Text style={s.lead}>See what has been reported around you.</Text></View><Pressable onPress={locate} accessibilityLabel="Center map on my location" style={s.locate}><Ionicons name="locate-outline" size={21} color={colors.accent} /></Pressable></View>
    <View style={s.mapWrap}><IssueMap issues={shown} center={center} onSelect={setSelected} /></View>{selected && <Pressable onPress={() => router.push(`/issue/${selected.id}`)} style={s.selected}><View style={{ flex: 1 }}><Text style={s.selectedLabel}>SELECTED REPORT</Text><Text style={s.selectedTitle}>{selected.title}</Text><Text style={s.selectedLocation}>{selected.address}</Text></View><Ionicons name="arrow-forward" size={18} color={colors.accent} /></Pressable>}
    <View style={s.search}><Ionicons name="search-outline" size={20} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search street, issue, or reference" placeholderTextColor={colors.muted} style={s.searchInput} accessibilityLabel="Search public reports" />{search ? <Pressable onPress={() => setSearch('')} accessibilityLabel="Clear search"><Ionicons name="close-circle" size={19} color={colors.muted} /></Pressable> : null}</View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(item => <Pressable key={item.value} onPress={() => setFilter(item.value)} style={[s.filter, filter === item.value && s.filterActive]}><Text style={[s.filterText, filter === item.value && s.filterTextActive]}>{item.label}</Text></Pressable>)}</ScrollView>
    <SectionHeading eyebrow="PUBLIC REPORTS" title={`${shown.length} ${shown.length === 1 ? 'report' : 'reports'}`} />{loading ? <ActivityIndicator color={colors.accent} style={{ margin: 32 }} /> : error ? <EmptyState icon="cloud-offline-outline" title="Map data unavailable" detail={error} /> : shown.length ? shown.map(item => <IssueCard key={item.id} issue={item} compact />) : <EmptyState icon="search-outline" title="No matching reports" detail="Try another search or status. Reports with a pinned location also appear on the map." />}
  </ScrollView></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, content: { width: '100%', maxWidth: 800, alignSelf: 'center', padding: 20, paddingBottom: 36 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, eyebrow: { color: colors.accent, fontFamily: 'Inter_600SemiBold', fontSize: 11, letterSpacing: 1.5 }, title: { color: colors.ink, fontFamily: 'SpaceGrotesk_700Bold', fontSize: 30, letterSpacing: -1, marginTop: 5 }, lead: { color: colors.inkSoft, fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 5 }, locate: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, alignItems: 'center', justifyContent: 'center' }, mapWrap: { marginBottom: 12 }, selected: { backgroundColor: colors.paperRaised, borderColor: colors.rule, borderWidth: 1, borderRadius: 15, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 13 }, selectedLabel: { color: colors.accent, fontFamily: 'Inter_600SemiBold', fontSize: 10, letterSpacing: 1.2 }, selectedTitle: { color: colors.ink, fontFamily: 'SpaceGrotesk_600SemiBold', fontSize: 15, marginTop: 4 }, selectedLocation: { color: colors.muted, fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 4 }, search: { height: 48, borderRadius: 14, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, marginTop: 8 }, searchInput: { flex: 1, color: colors.ink, fontFamily: 'Inter_400Regular', fontSize: 14 }, filters: { gap: 8, paddingVertical: 16, marginBottom: 9 }, filter: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 99, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, filterActive: { backgroundColor: colors.accent, borderColor: colors.accent }, filterText: { color: colors.inkSoft, fontFamily: 'Inter_600SemiBold', fontSize: 12 }, filterTextActive: { color: colors.accentInk } });
